name: gh-traffic-stats
on:
  schedule:
    - cron: "30 0 * * *" # Runs automatically every single night
  workflow_dispatch: # Lets you trigger it manually

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: gtapps/gh-traffic-stats@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}