name: gh-traffic-stats
on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Explicitly tells GitHub this job has write access
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: GitHub Traffic Sync
        uses: HustonMccallister/repository-traffic-action@v1.0.1
        env:
          FEED_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          STATIC_BUILD: true
